from typing import TypedDict

class CampaignState(TypedDict):
    # Information entered by the user
    product: str
    audience: str
    tone: str

    # Generated by AI
    content: str
    keywords: str
    hashtags: str
    image_prompt: str
    final_content: str